const express = require("express");
const sql = require("mssql");

/**
 * Creates and configures a router for fetching currently signed-in visitor data
 * using Azure SQL.
 *
 * @param {object} dbService - The Azure SQL database service wrapper (e.g., with executeQuery).
 * @returns {express.Router} - An Express router with the visitor endpoints.
 */
function createVisitorsRouter(dbService) {
  const router = express.Router();

  // Endpoint to get all currently signed-in visitors
  router.get("/visitors", async (req, res) => {
    // T-SQL query to retrieve all active visits (where exit_time IS NULL)
    // and aggregate the related dependent data using FOR JSON PATH.
    const query = `
      SELECT
        T1.id,
        T1.first_name,
        T1.last_name,
        T1.photo_path,
        T1.is_banned,
        T2.entry_time,
        T2.exit_time,
        T2.known_as,
        T2.address,
        T2.phone_number,
        T2.unit,
        T2.reason_for_visit,
        T2.company_name,
        T2.type,
        T2.mandatory_acknowledgment_taken,
        (
            SELECT 
                full_name, 
                age 
            FROM dependents AS T3 
            WHERE T3.visit_id = T2.id
            FOR JSON PATH
        ) AS additional_dependents
      FROM visitors AS T1
      JOIN visits AS T2
        ON T1.id = T2.visitor_id
      WHERE T2.exit_time IS NULL
      GROUP BY 
        T1.id, T1.first_name, T1.last_name, T1.photo_path, T1.is_banned,
        T2.id, T2.entry_time, T2.exit_time, T2.known_as, T2.address, T2.phone_number,
        T2.unit, T2.reason_for_visit, T2.company_name, T2.type, T2.mandatory_acknowledgment_taken
      ORDER BY T2.entry_time DESC;
    `;

    try {
      const result = await dbService.executeQuery(query);
      const rows = result.recordset;

      const resultsWithUrls = rows.map((row) => {
        let dependentsData = [];

        // Parse the JSON array string generated by FOR JSON PATH
        if (row.additional_dependents) {
          try {
            dependentsData = JSON.parse(row.additional_dependents);
          } catch (parseErr) {
            console.error(
              "Failed to parse dependents JSON for active visitor:",
              parseErr.message
            );
          }
        }

        return {
          ...row,
          // Construct the full photo URL
          photo: row.photo_path
            ? `${req.protocol}://${req.get("host")}/${row.photo_path}`
            : null,
          dependents: dependentsData,
          // Clean up the response object
          photo_path: undefined,
          additional_dependents: undefined,
        };
      });

      res.json(resultsWithUrls);
    } catch (err) {
      console.error("Azure SQL Error in GET /visitors:", err.message);
      res
        .status(500)
        .json({ error: "Failed to retrieve active visitor data." });
    }
  });

  return router;
}

module.exports = createVisitorsRouter;
